In [1]:
from manipulator import * 
from obstacle import *
import numpy as np 

### Manipulator

#### Coordinates

In [3]:
manipulator = Manipulator(
     joint_num=3,
     joint_angles=[0, np.pi / 3, np.pi / 3]
)
manipulator.get_joint_coordinates().astype('float16')

array([[ 0.   ,  0.   ,  0.   ],
       [ 0.5  ,  0.   ,  0.866],
       [ 1.   ,  0.   , -0.   ]], dtype=float16)

In [4]:
manipulator = Manipulator(
     joint_num=3,
     joint_angles=[np.pi / 2, np.pi / 3, np.pi / 3]
)
manipulator.get_joint_coordinates().astype('float16')

array([[ 0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.5  ,  0.866],
       [ 0.   ,  1.   , -0.   ]], dtype=float16)

In [5]:
manipulator = Manipulator(
     joint_num=3,
     joint_angles=[np.pi / 4, np.pi / 3, np.pi / 3]
)
manipulator.get_joint_coordinates().astype('float16')

array([[ 0.    ,  0.    ,  0.    ],
       [ 0.3535,  0.3535,  0.866 ],
       [ 0.707 ,  0.707 , -0.    ]], dtype=float16)

In [3]:
manipulator = Manipulator(
     joint_num=5,
     joint_angles=[0, np.pi / 3, np.pi / 3, np.pi, 4 / 3 * np.pi]
)
manipulator.get_joint_coordinates().astype('float16')

array([[ 0.   ,  0.   ,  0.   ],
       [ 0.5  ,  0.   ,  0.866],
       [ 1.   ,  0.   , -0.   ],
       [ 1.5  ,  0.   , -0.866],
       [ 2.5  ,  0.   , -0.866]], dtype=float16)

#### Successors

In [6]:
manipulator = Manipulator(
     joint_num=5,
     angle_delta=np.pi / 90,
     joint_angles=[0, np.pi / 3, np.pi / 3, np.pi, 4 / 3 * np.pi]
)
successors = manipulator.get_successors()

In [8]:
print("init coordinates:") 
print(manipulator.get_joint_coordinates().astype('float16'))
assert(len(successors) == 2 * manipulator.joint_num)
for i in range(len(successors)): 
    print(f"successors {i}:")
    print(successors[i].get_joint_coordinates().astype('float16'))

init coordinates:
[[ 0.     0.     0.   ]
 [ 0.5    0.     0.866]
 [ 1.     0.    -0.   ]
 [ 1.5    0.    -0.866]
 [ 2.5    0.    -0.866]]
successors 0:
[[ 0.       0.       0.     ]
 [ 0.4998  -0.01746  0.866  ]
 [ 0.9995  -0.0349  -0.     ]
 [ 1.499   -0.05234 -0.866  ]
 [ 2.498   -0.0872  -0.866  ]]
successors 1:
[[ 0.       0.       0.     ]
 [ 0.4998   0.01746  0.866  ]
 [ 0.9995   0.0349  -0.     ]
 [ 1.499    0.05234 -0.866  ]
 [ 2.498    0.0872  -0.866  ]]
successors 2:
[[ 0.      0.      0.    ]
 [ 0.53    0.      0.848 ]
 [ 0.9995  0.     -0.0349]
 [ 1.469   0.     -0.918 ]
 [ 2.469   0.     -0.9526]]
successors 3:
[[ 0.      0.      0.    ]
 [ 0.4695  0.      0.883 ]
 [ 0.9995  0.      0.0349]
 [ 1.529   0.     -0.813 ]
 [ 2.53    0.     -0.7783]]
successors 4:
[[ 0.       0.       0.     ]
 [ 0.5      0.       0.866  ]
 [ 0.969    0.      -0.01692]
 [ 1.438    0.      -0.9    ]
 [ 2.438    0.      -0.9346 ]]
successors 5:
[[ 0.       0.       0.     ]
 [ 0.5      0.       0

### Obstacles

#### Sphere obstacles

In [9]:
manipulator = Manipulator(
     joint_num=5,
     angle_delta=np.pi / 90,
     joint_angles=[0, np.pi / 3, np.pi / 3, np.pi, 4 / 3 * np.pi]
)
successors = manipulator.get_successors()

In [10]:
obstacle1 = SphereObstacle(
    center=np.array([0.5, 0, 0]),
    r=0.25,
)

obstacle2 = SphereObstacle(
    center=np.array([0.8, 0.1, 0.4]), 
    r=0.2,
)

obstacle3 = SphereObstacle(
    center=np.array([0.8, 0.1, 0.4]), 
    r=0.1,
)

assert(~obstacle1.intersect(manipulator))
assert(obstacle2.intersect(manipulator))
assert(~obstacle3.intersect(manipulator))

#### Polygon obstacles